# This rule is not used by the project controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over crd.devops.toolbox.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: raytracker-admin-role
rules:
- apiGroups:
  - crd.devops.toolbox
  resources:
  - raytrackers
  verbs:
  - '*'
- apiGroups:
  - crd.devops.toolbox
  resources:
  - raytrackers/status
  verbs:
  - get
