# This rule is not used by the project controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to crd.devops.toolbox resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: raytracker-viewer-role
rules:
- apiGroups:
  - crd.devops.toolbox
  resources:
  - raytrackers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crd.devops.toolbox
  resources:
  - raytrackers/status
  verbs:
  - get
