# This rule is not used by the project controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the crd.devops.toolbox.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: raytracker-editor-role
rules:
- apiGroups:
  - crd.devops.toolbox
  resources:
  - raytrackers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.devops.toolbox
  resources:
  - raytrackers/status
  verbs:
  - get
