---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - crd.devops.toolbox
  resources:
  - podtrackers
  - raytrackers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.devops.toolbox
  resources:
  - podtrackers/finalizers
  - raytrackers/finalizers
  verbs:
  - update
- apiGroups:
  - crd.devops.toolbox
  resources:
  - podtrackers/status
  - raytrackers/status
  verbs:
  - get
  - patch
  - update
