apiVersion: crd.devops.toolbox/v1
kind: RayTracker
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: raytracker-sample
spec:
  # TODO(user): Add fields here
