apiVersion: crd.devops.toolbox/v1
kind: PodTracker
metadata:
  name: podtracker-sample
spec:
  name: "test-podtracker"
  ImageSpec:
    image: "elasticsearch/kibana"
    version: "parspooyesh"
    repository: "registry.parspooyesh.net"
    token: "my_valid_token2"
status:
  conditions:
    - type: "PodAvailable"
      status: "False"
      reason: "Initializing"
      message: "Pod is being created"
      lastTransitionTime: "2025-10-05T08:00:00Z"
