apiVersion: crd.devops.toolbox/v1
kind: PodTracker
metadata:
  name: podtracker-sample
spec:
  name: "test-podtracker"
  reporter:
    kind: "logstash"
    key: "parspooyesh"
    channel: "registry.parspooyesh.net/elasticsearch"
status:
  conditions:
    - type: "PodAvailable"
      status: "False"
      reason: "Initializing"
      message: "Pod is being created"
      lastTransitionTime: "2025-10-05T08:00:00Z"
